name = "ProfileSVG"
uuid = "132c30aa-f267-4189-9183-c8a63c7e05e6"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Colors = "0.10, 0.11, 0.12"
FlameGraphs = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
